# window rules
windowrule=tags:5,isopensilent:1,appid:ZapZap
windowrule=tags:9,appid:com.github.th_ch.youtube_music

# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
