# window rules
windowrule=tags:5,isopensilent:1,appid:ZapZap
windowrule=focused_opacity:0.9,isopensilent:1,appid:ZapZap
windowrule=unfocused_opacity:0.8,isopensilent:1,appid:ZapZap

windowrule=tags:5,isopensilent:1,appid:vesktop
windowrule=focused_opacity:0.9,isopensilent:1,appid:vesktop
windowrule=unfocused_opacity:0.8,isopensilent:1,appid:vesktop

windowrule=tags:9,appid:com.github.th_ch.youtube_music
windowrule=focused_opacity:0.9,isopensilent:1,appid:com.github.th_ch.youtube_music
windowrule=unfocused_opacity:0.8,isopensilent:1,appid:com.github.th_ch.youtube_music


# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
